---
- name: Provisionar servidor DNS
  hosts: tierra
  become: true
  tasks:
    - name: Actualizar lista de paquetes
      ansible.builtin.package:
        update_cache: true

    - name: Instalar Bind9
      ansible.builtin.package:
        name:
        - bind9
        - bind9-utils
        - bind9-doc

    - name: Configurar Bind9 named
      ansible.builtin.copy:
        src: ../dns/named
        dest: /etc/default/

    - name: Configurar Bind9 conf
      ansible.builtin.copy:
        src: ../dns/named.conf.local
        dest: /etc/bind

    - name: Configurar Bind9 conf
      ansible.builtin.copy:
        src: ../dns/named.conf.options
        dest: /etc/bind

    - name: Configurar Bind9 dbs
      ansible.builtin.copy:
        src: ../dns/db.sistema.sol
        dest: /var/lib/bind

    - name: Configurar Bind9 dbs
      ansible.builtin.copy:
        src: ../dns/db.192.168.56
        dest: /var/lib/bind

    - name: Comprobar que funciona
      command: named-checkconf

    - name: Reiniciar servicio Bind9
      systemd:
        name: bind9
        enabled: true
        state: restarted
    
    - name: Crear usuario "pepe"
      ansible.builtin.user:
        name: pepe
        shell: /bin/bash
        create_home: yes
        password: ""
    
    - name: Copiar el directorio "pruebasFTP"con el archivo "datos1.txt"
      ansible.builtin.copy:
        src: ../usuarios/pepe/pruebasFTP
        dest: /home/pepe
    
    - name: Instalar vsftpd
      ansible.builtin.package:
        name:
        - vsftpd
        
    - name: Crear usuario "luis"
      ansible.builtin.user:
        name: luis
        shell: /bin/bash
        create_home: yes
        password: ""

    - name: Copiar los archivos "luis1.txt" y "luis2.txt"
      ansible.builtin.copy:
        src: ../usuarios/luis/
        dest: /home/luis
      
    - name: Crear usuario "maria"
      ansible.builtin.user:
        name: maria
        shell: /bin/bash
        create_home: yes
        password: ""
      
    - name: Copiar los archivos "maria1.txt" y "maria2.txt"
      ansible.builtin.copy:
        src: ../usuarios/maria/
        dest: /home/maria

    - name: Crear usuario "miguel"
      ansible.builtin.user:
        name: miguel
        shell: /bin/bash
        create_home: yes
        password: ""